name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello, world!"
      - run: ls -l
      - uses: actions/checkout@v4
      - run: ls -l
      
